[package]
name = "cli-rs-command-gen"
version = "0.1.8"
edition = "2021"
description = "internal helper for cli-rs"
license = "UNLICENSE"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
